name: integracion workflow

on: 
  push:
    branches: [main]

jobs:
  ci_to_master:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16.13.1

      - run: sudo apt install chromium-browser
      - run: npm ci
      
      - name: 'NPM test'
        run: |
              export CHROME_BIN=/usr/bin/chromium-browser
              CI=true npm run test
        run: npm run test
        env:
          CI: true
