name: integracion workflow

on: 
  push:
    branches: [main]

jobs:
  ci_to_master:
    runst-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 10
      - run: npm ci
      - run: npm test
      - run: npm run build